[package]
name = "novel-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "novel_core"

[dependencies]
diesel = { version = "2.2", features = ["sqlite"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
